/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Canvas;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Alejandro Riveros
 */
public class Vista extends javax.swing.JFrame {
    private Modelo modelo;
    private Controlador control;
    /**
     * Creates new form Vista
     */
    public Vista(Modelo m) {
        modelo=m;
        initComponents();
        grupoBotones();
        capturarEventos();
    }
    public Controlador getControl() {
        if(control == null){
            control = new Controlador(this);
        }
        return control;
    }

    public Canvas getLienzo() {
        return lienzo1;
    }

    public void setLienzo(Canvas lienzo) {
        this.lienzo1 = lienzo;
    }
    
    private void capturarEventos() {
        boton.addActionListener(getControl());
    }

    public JLabel getLabelMensaje() {
        return labelMensaje;
    }
    
    
    private void grupoBotones(){
        buttonGroup1.add(radioBoton1);
        buttonGroup1.add(radioBoton2);
        buttonGroup1.add(radioBoton3);
        buttonGroup1.add(radioBoton4);
        buttonGroup1.add(radioBoton5);
        buttonGroup1.add(radioBoton6);
        buttonGroup1.add(radioBoton7);
        buttonGroup1.add(radioBoton8);
        buttonGroup1.add(radioBoton9);
        buttonGroup1.add(radioBoton10);                                            
    }
    public void apagarBotones(){
        radioBoton1.setEnabled(false);
        radioBoton2.setEnabled(false);
        radioBoton3.setEnabled(false);
        radioBoton4.setEnabled(false);
        radioBoton5.setEnabled(false);
        radioBoton6.setEnabled(false);
        radioBoton7.setEnabled(false);
        radioBoton8.setEnabled(false);
        radioBoton9.setEnabled(false);
        radioBoton10.setEnabled(false);
    }
    public void encenderBotones() {
        radioBoton1.setEnabled(true);
        radioBoton2.setEnabled(true);
        radioBoton3.setEnabled(true);
        radioBoton4.setEnabled(true);
        radioBoton5.setEnabled(true);
        radioBoton6.setEnabled(true);
        radioBoton7.setEnabled(true);
        radioBoton8.setEnabled(true);
        radioBoton9.setEnabled(true);
        radioBoton10.setEnabled(true);
    }
    public int rbtnSeleccionado(){
        if(radioBoton1.isSelected()){
            return 1;
        }else if(radioBoton2.isSelected()){
            return 2;
        }else if(radioBoton3.isSelected()){
            return 3;
        }else if(radioBoton4.isSelected()){
            return 4;
        }else if(radioBoton5.isSelected()){
            return 5;
        }else if(radioBoton6.isSelected()){
            return 6;
        }else if(radioBoton7.isSelected()){
            return 7;
        }else if(radioBoton8.isSelected()){
            return 8;
        }else if(radioBoton9.isSelected()){
            return 9;
        }else if(radioBoton10.isSelected()){
            return 10;
        }else{
            return 0;
        }
    }
    public void lblMensaje(){
        if(radioBoton1.isSelected() || radioBoton2.isSelected() || radioBoton3.isSelected() || radioBoton4.isSelected()|| 
        radioBoton5.isSelected() || radioBoton6.isSelected() || radioBoton7.isSelected() || radioBoton8.isSelected() || radioBoton9.isSelected() || radioBoton10.isSelected()){
            labelMensaje.setText("");
        }else{
            labelMensaje.setText("Escoge fractal");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    public JButton getBoton() {
        return boton;
    }

    public void setBoton(JButton boton) {
        this.boton = boton;
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        radioBoton1 = new javax.swing.JRadioButton();
        radioBoton2 = new javax.swing.JRadioButton();
        radioBoton3 = new javax.swing.JRadioButton();
        radioBoton4 = new javax.swing.JRadioButton();
        radioBoton5 = new javax.swing.JRadioButton();
        radioBoton6 = new javax.swing.JRadioButton();
        radioBoton7 = new javax.swing.JRadioButton();
        radioBoton8 = new javax.swing.JRadioButton();
        radioBoton9 = new javax.swing.JRadioButton();
        radioBoton10 = new javax.swing.JRadioButton();
        boton = new javax.swing.JButton();
        lienzo = new java.awt.Canvas();
        lienzo1 = new java.awt.Canvas();
        labelMensaje = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        radioBoton1.setText("Fractal 1");

        radioBoton2.setText("Fractal 2");

        radioBoton3.setText("Fractal 3");

        radioBoton4.setText("Fractal 4");

        radioBoton5.setText("Fractal 5");

        radioBoton6.setText("Fractal 6");

        radioBoton7.setText("Fractal 7");

        radioBoton8.setText("Fractal 8");

        radioBoton9.setText("Fractal 9");

        radioBoton10.setText("Fractal 10");

        boton.setText("Iniciar");

        lienzo.setBackground(new java.awt.Color(0, 0, 0));

        lienzo1.setBackground(new java.awt.Color(0, 0, 0));

        labelMensaje.setText("Mensaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioBoton10)
                            .addComponent(radioBoton9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(radioBoton8)
                                .addComponent(radioBoton7)
                                .addComponent(radioBoton6)
                                .addComponent(radioBoton5)
                                .addComponent(radioBoton4)
                                .addComponent(radioBoton3)
                                .addComponent(radioBoton2)
                                .addComponent(radioBoton1))
                            .addComponent(labelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lienzo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioBoton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBoton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBoton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBoton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBoton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBoton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBoton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBoton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBoton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioBoton10)
                        .addGap(27, 27, 27)
                        .addComponent(labelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Modelo getModelo() {
        return modelo;//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel labelMensaje;
    private java.awt.Canvas lienzo;
    private java.awt.Canvas lienzo1;
    private javax.swing.JRadioButton radioBoton1;
    private javax.swing.JRadioButton radioBoton10;
    private javax.swing.JRadioButton radioBoton2;
    private javax.swing.JRadioButton radioBoton3;
    private javax.swing.JRadioButton radioBoton4;
    private javax.swing.JRadioButton radioBoton5;
    private javax.swing.JRadioButton radioBoton6;
    private javax.swing.JRadioButton radioBoton7;
    private javax.swing.JRadioButton radioBoton8;
    private javax.swing.JRadioButton radioBoton9;
    // End of variables declaration//GEN-END:variables

}
